services:
  postgres:
    extends:
      file: db/docker-compose.postgres.yml
      service: postgres

  auth-service:
    build:
      context: . # чтобы иметь возможность загружать файлы за докерфайлом (requirements-base.txt)
      dockerfile: ./services/auth/Dockerfile
    env_file:
      - ./services/auth/.env  # Загружаем переменные из .env файла сервиса
    depends_on:
      # Ожидаем готовности Postgres перед запуском сервиса
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      # Монтируем код для разработки (hot-reload)
      - ./services/auth:/app
